server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://paperdb.cyikbwlysj6o.ap-northeast-2.rds.amazonaws.com:3306/Paper_DB?autoReconnect=true&ServerTimezone=UTC # 변경해주세요
    username: admin # 변경해주세요
    password: ss93121614! # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
  sql:
    init:
      platform: mysql